source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '3.2.14'

# Use postgresql as the database for Active Record
gem 'pg'

# Use SCSS for stylesheets
gem 'sass-rails'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails'

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem "subscribem", :path => "../subscribem"
gem 'friendly_id'
gem 'cancan'
gem "forem", :github => "radar/forem", :branch => 'master'
gem "kaminari", "0.14.1"
gem 'apartment', :github => "radar/aparment", :branch => "master"

group :development, :test do
  gem 'rspec-rails', '2.14.0'
  gem 'capybara', '2.1.0'
  gem 'factory_girl', '4.2.0'
  gem 'database_cleaner', '1.0.1'
  gem 'fake_braintree_redirect', :github => "radar/fake_braintree_redirect"
  gem 'pry'
end